In [28]:
# imports
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import sys
import os
import warnings
import statistics as st 
from sklearn.preprocessing import StandardScaler, normalize             # data scaling and normalization
from sklearn.cluster import kmeans
from scipy.spatial.distance import cdist
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from ipython.display import image
pio.renderers
warnings.filterwarnings("ignore")                                                # for statistical analysis

ImportError: cannot import name '_check_sample_weight' from 'sklearn.utils.validation' (c:\Users\HP\Anaconda3\lib\site-packages\sklearn\utils\validation.py)

In [2]:

sys.path.append('.')
sys.path.append('..')
sys.path.append('../scripts')

from clean_dataframe import Clean_DataFrame
from visualize_dataframe import VisualizeDataframe
from utility import Utility

c:\Users\HP\Anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [14]:
#read clean and aggregated data
df = pd.read_csv('../data/telecom_clean_data.csv')
df

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Total DL (Bytes),total_google_DV,total_youtube_DV,total_email_DV,total_gaming_DV,total_netflix_DV,total_social_DV,total_other_DV,total_DV,total_social_media_DV
0,1.311448e+19,2019-04-04 12:01:18,770.0,2019-04-25 14:35:31,662.0,86399.0,2.082014e+14,3.366496e+10,3.552121e+13,9164566995485190,...,308879636.0,2905912.0,18355943.0,3701304.0,292426453.0,17855187.0,1570185.0,180558843.0,345629377.0,1570185.0
1,1.311448e+19,2019-04-09 13:04:04,235.0,2019-04-25 08:15:48,606.0,86399.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,653384965.0,4414096.0,39359124.0,937385.0,609920783.0,35565545.0,1933278.0,541959383.0,707185356.0,1933278.0
2,1.311448e+19,2019-04-09 17:42:11,1.0,2019-04-25 11:58:13,652.0,86399.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,279807335.0,10229119.0,34425237.0,3363124.0,229980251.0,23751202.0,1726277.0,414908351.0,307690973.0,1726277.0
3,1.311448e+19,2019-04-10 00:31:25,486.0,2019-04-25 07:36:35,171.0,86399.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,846028530.0,11811761.0,36534765.0,2070983.0,810387875.0,15092588.0,657493.0,761837216.0,889352748.0,657493.0
4,1.311448e+19,2019-04-12 20:10:23,565.0,2019-04-25 10:40:32,954.0,86399.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,569138589.0,7748843.0,34222253.0,2110349.0,531237049.0,17539799.0,912788.0,564619822.0,607681403.0,912788.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149993,1.311448e+19,2019-04-29 07:28:41,79.0,2019-04-30 18:22:23,512.0,125622.0,2.082014e+14,3.362611e+10,3.573531e+13,D73542B,...,623318363.0,12459876.0,26306531.0,2555578.0,571286842.0,40974659.0,2307959.0,179348636.0,666947481.0,2307959.0
149994,1.311448e+19,2019-04-29 07:28:41,83.0,2019-04-30 15:01:06,268.0,113545.0,2.082003e+14,3.364566e+10,3.515541e+13,T88383B,...,862796008.0,8922614.0,42219856.0,1565542.0,825524976.0,28354119.0,892867.0,792559807.0,922173944.0,892867.0
149995,1.304243e+19,2019-04-29 07:28:41,615.0,2019-04-30 00:01:49,407.0,59587.0,2.082014e+14,3.366865e+10,3.533251e+13,T85721A,...,819016468.0,1265634.0,24553645.0,4280107.0,797160102.0,29618711.0,993175.0,336273648.0,872761860.0,993175.0
149996,7.277826e+18,2019-04-29 07:28:42,451.0,2019-04-30 06:02:33,214.0,81230.0,2.082022e+14,3.365069e+10,3.548311e+13,D20434A,...,574175259.0,12784914.0,27955095.0,690876.0,535806880.0,37561864.0,3517065.0,16751926.0,631804110.0,3517065.0
149997,7.349883e+18,2019-04-29 07:28:42,483.0,2019-04-30 10:41:33,187.0,97970.0,2.082019e+14,3.366345e+10,3.566051e+13,D10223C,...,666648844.0,4415361.0,22165518.0,2121718.0,631628095.0,40643294.0,2352181.0,714638145.0,705783925.0,2352181.0

In [13]:
#df instances
cleaner = Clean_DataFrame(df)
visualizer = VisualizeDataframe(df)
df.columns.tolist()

initializing dataframe

['Bearer Id',
 'Start',
 'Start ms',
 'End',
 'End ms',
 'Dur. (ms)',
 'IMSI',
 'MSISDN/Number',
 'IMEI',
 'Last Location Name',
 'Avg RTT DL (ms)',
 'Avg RTT UL (ms)',
 'Avg Bearer TP DL (kbps)',
 'Avg Bearer TP UL (kbps)',
 'TCP DL Retrans. Vol (Bytes)',
 'TCP UL Retrans. Vol (Bytes)',
 'DL TP < 50 Kbps (%)',
 '50 Kbps < DL TP < 250 Kbps (%)',
 '250 Kbps < DL TP < 1 Mbps (%)',
 'DL TP > 1 Mbps (%)',
 'UL TP < 10 Kbps (%)',
 '10 Kbps < UL TP < 50 Kbps (%)',
 '50 Kbps < UL TP < 300 Kbps (%)',
 'UL TP > 300 Kbps (%)',
 'HTTP DL (Bytes)',
 'HTTP UL (Bytes)',
 'Activity Duration DL (ms)',
 'Activity Duration UL (ms)',
 'Dur. (ms).1',
 'Handset Manufacturer',
 'Handset Type',
 'Nb of sec with 125000B < Vol DL',
 'Nb of sec with 1250B < Vol UL < 6250B',
 'Nb of sec with 31250B < Vol DL < 125000B',
 'Nb of sec with 37500B < Vol UL',
 'Nb of sec with 6250B < Vol DL < 31250B',
 'Nb of sec with 6250B < Vol UL < 37500B',
 'Nb of sec with Vol DL < 6250B',
 'Nb of sec with Vol UL < 1250B',
 'Social Media DL (Bytes)',
 'Social Media UL (Bytes)',
 'Google DL (Bytes)',
 'Google UL (Bytes)',
 'Email DL (Bytes)',
 'Email UL (Bytes)',
 'Youtube DL (Bytes)',
 'Youtube UL (Bytes)',
 'Netflix DL (Bytes)',
 'Netflix UL (Bytes)',
 'Gaming DL (Bytes)',
 'Gaming UL (Bytes)',
 'Other DL (Bytes)',
 'Other UL (Bytes)',
 'Total UL (Bytes)',
 'Total DL (Bytes)',
 'total_google_DV',
 'total_youtube_DV',
 'total_email_DV',
 'total_gaming_DV',
 'total_netflix_DV',
 'total_social_DV',
 'total_other_DV']

## User Engagemnet Analysis

In [15]:
user_engagement_df = df[['MSISDN/Number', 'Bearer Id', 'Dur. (ms)', 'total_DV']]

user_engagement_df = user_engagement_df.groupby('MSISDN/Number').agg(
    {'Bearer Id': 'count', 'Dur. (ms)': 'sum', 'total_DV': 'sum'})
user_engagement_df = user_engagement_df.rename(columns={'Bearer Id': 'XDR Sessions'})
user_engagement_df

               XDR Sessions  Dur. (ms)      total_DV
MSISDN/Number
3.360100e+10              1   116720.0  8.786906e+08
3.360100e+10              1   181230.0  1.568596e+08
3.360100e+10              1   134969.0  5.959665e+08
3.360101e+10              1    49878.0  4.223207e+08
3.360101e+10              2    37104.0  1.457411e+09
...                     ...        ...           ...
3.379000e+10              1     8810.0  7.146416e+08
3.379000e+10              1   140988.0  4.803073e+08
3.197021e+12              1    86399.0  2.321240e+08
3.370000e+14              1    86399.0  5.962878e+08
8.823971e+14              1    86399.0  1.198411e+08

[106854 rows x 3 columns]

In [16]:
user_engagement_df['XDR Sessions'].value_counts()

1       77728
2       21452
3        4422
4        1950
5         938
6         208
7          75
8          34
9          17
10         12
12          5
11          5
17          2
15          2
18          1
16          1
1066        1
13          1
Name: XDR Sessions, dtype: int64

In [17]:
user_engagement_df['Dur. (ms)'].value_counts()

86399.0     11058
86400.0      2015
172798.0     1430
172799.0      719
259197.0      324
            ...
15558.0         1
208656.0        1
377915.0        1
43220.0         1
140988.0        1
Name: Dur. (ms), Length: 73942, dtype: int64

In [19]:
user_engagement_df['total_DV'].value_counts()

4.770374e+08    2
6.377260e+08    2
3.212946e+08    2
3.752936e+08    2
8.786906e+08    1
               ..
1.089531e+09    1
9.172005e+08    1
8.083350e+08    1
6.432406e+08    1
1.198411e+08    1
Name: total_DV, Length: 106850, dtype: int64

### Top 10 customers per engagement matric - XDR Sessions

In [20]:
user_engagement_df.nlargest(10, 'XDR Sessions')

               XDR Sessions   Dur. (ms)      total_DV
MSISDN/Number
3.366371e+10           1066  63940818.0  5.302862e+11
3.362632e+10             18   1785419.0  7.951348e+09
3.361489e+10             17   1678397.0  8.826326e+09
3.362578e+10             17   1599052.0  8.474657e+09
3.365973e+10             16   1905478.0  7.680848e+09
3.367588e+10             15   1745131.0  7.891111e+09
3.376054e+10             15   1651084.0  8.495067e+09
3.366716e+10             13   1209703.0  5.618394e+09
3.360313e+10             12   1109736.0  4.976195e+09
3.360452e+10             12   1193033.0  5.487855e+09

### Top 10 Customer per engagement metric - Duration

In [21]:
user_engagement_df.nlargest(10, 'Dur. (ms)')

               XDR Sessions   Dur. (ms)      total_DV
MSISDN/Number
3.366371e+10           1066  63940818.0  5.302862e+11
3.365973e+10             16   1905478.0  7.680848e+09
3.362632e+10             18   1785419.0  7.951348e+09
3.365936e+10             11   1747994.0  4.658437e+09
3.367588e+10             15   1745131.0  7.891111e+09
3.361489e+10             17   1678397.0  8.826326e+09
3.376054e+10             15   1651084.0  8.495067e+09
3.362578e+10             17   1599052.0  8.474657e+09
3.378632e+10             12   1427807.0  5.622232e+09
3.366471e+10             11   1334982.0  6.852224e+09

### Top 10 customers per engagement metric - Total data volume

In [23]:
user_engagement_df.nlargest(10, 'total_DV')

               XDR Sessions   Dur. (ms)      total_DV
MSISDN/Number
3.366371e+10           1066  63940818.0  5.302862e+11
3.361489e+10             17   1678397.0  8.826326e+09
3.376054e+10             15   1651084.0  8.495067e+09
3.362578e+10             17   1599052.0  8.474657e+09
3.362632e+10             18   1785419.0  7.951348e+09
3.367588e+10             15   1745131.0  7.891111e+09
3.365973e+10             16   1905478.0  7.680848e+09
3.366646e+10             11   1168703.0  7.308501e+09
3.376041e+10             12   1248477.0  7.112835e+09
3.366471e+10             11   1334982.0  6.852224e+09

#### Normalizing each engagement metric and runing a k-means (k=3) to classify customers in three groups of engagement.